/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package empaquetado;

import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author ASUS
 */
public class Catalogo_frame extends javax.swing.JFrame {
    
    ArrayList<String> carrito = new ArrayList<>();
    
    Lista listaCatalogo = new Lista();
    Pila historialPila = new Pila();
    Cola colaPedidos = new Cola();

    /**
     * Creates new form Catalogo_frame
     */
    public Catalogo_frame() {
        initComponents();
        
        listaCatalogo.setCargarCatalogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnac = new javax.swing.JButton();
        btnaj = new javax.swing.JButton();
        btnag = new javax.swing.JButton();
        btnaz = new javax.swing.JButton();
        btnacs = new javax.swing.JButton();
        btnap = new javax.swing.JButton();
        btnam = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btngc = new javax.swing.JButton();
        btnep = new javax.swing.JButton();
        btnh = new javax.swing.JButton();
        btndh = new javax.swing.JButton();
        btngp = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 18)); // NOI18N
        jLabel1.setText("Catálogo");

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel2.setText("Camiseta");

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel3.setText("Jeans");

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel4.setText("Gorra");

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel5.setText("Zapatos");

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel6.setText("Medias");

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel7.setText("Camisa");

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel8.setText("Pantaloneta");

        jButton1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jButton1.setText("Ver carrito");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnac.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        btnac.setText("Agregar");
        btnac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacActionPerformed(evt);
            }
        });

        btnaj.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        btnaj.setText("Agregar");
        btnaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajActionPerformed(evt);
            }
        });

        btnag.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        btnag.setText("Agregar");
        btnag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagActionPerformed(evt);
            }
        });

        btnaz.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        btnaz.setText("Agregar");
        btnaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnazActionPerformed(evt);
            }
        });

        btnacs.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        btnacs.setText("Agregar");
        btnacs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacsActionPerformed(evt);
            }
        });

        btnap.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        btnap.setText("Agregar");
        btnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnapActionPerformed(evt);
            }
        });

        btnam.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        btnam.setText("Agregar");
        btnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnamActionPerformed(evt);
            }
        });

        jButton2.setText("Vaciar carrito");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btngc.setText("Guardar carrito");
        btngc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngcActionPerformed(evt);
            }
        });

        btnep.setText("Eliminar último producto");
        btnep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnepActionPerformed(evt);
            }
        });

        btnh.setText("Historial");
        btnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhActionPerformed(evt);
            }
        });

        btndh.setText("Deshacer");
        btndh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndhActionPerformed(evt);
            }
        });

        btngp.setText("Guardar pedido");
        btngp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(btnam)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnaj)
                                    .addComponent(btnag)
                                    .addComponent(btnh)
                                    .addComponent(btndh)
                                    .addComponent(btngp)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(btnac))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnaz)
                                        .addComponent(jButton1)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel7)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel5))
                                        .addComponent(jButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnap)
                                            .addComponent(btnacs))
                                        .addGap(14, 14, 14)))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btngc)
                                    .addComponent(btnep)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnac)
                            .addComponent(btnacs))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaj)
                    .addComponent(btnap, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnag)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnam))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnaz)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btngc))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(btnep)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnh)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btngp)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(carrito.isEmpty()){
            JOptionPane.showMessageDialog(this, "El carrito está vacío");
            return;
        }

        String mensaje = "Productos agregados al carrito:\n";

        for(String p : carrito){
            mensaje += p + "\n";
        }
        
        mensaje += "\nTotal de productos: " + carrito.size();
        
        JOptionPane.showMessageDialog(this, mensaje);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnapActionPerformed
        
        carrito.add("Pantaloneta");
        historialPila.setPush("c07", "Pantaloneta", 35000);
        colaPedidos.setEncolar("c07", "Pantaloneta", 35000);
        JOptionPane.showMessageDialog(this, "Pantaloneta agregada");
    }//GEN-LAST:event_btnapActionPerformed

    private void btnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnamActionPerformed
        
        carrito.add("Medias");
        historialPila.setPush("c05", "Medias", 10000);
        colaPedidos.setEncolar("c05", "Medias", 10000);
        JOptionPane.showMessageDialog(this, "Medias agregadas");
    }//GEN-LAST:event_btnamActionPerformed

    private void btnazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnazActionPerformed
        
        carrito.add("Zapatos");
        historialPila.setPush("c04", "Zapatos", 130000);
        colaPedidos.setEncolar("c04", "Zapatos", 130000);
        JOptionPane.showMessageDialog(this, "Zapatos agregados");
    }//GEN-LAST:event_btnazActionPerformed

    private void btnacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacActionPerformed
       
        carrito.add("Camiseta");
        historialPila.setPush("c01", "Camiseta", 40000);
        colaPedidos.setEncolar("c01", "Camiseta", 40000);
        JOptionPane.showMessageDialog(this, "Camiseta agregada");
    }//GEN-LAST:event_btnacActionPerformed

    private void btnagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagActionPerformed
        
        carrito.add("gorra");
        historialPila.setPush("c03", "Gorra", 25000);
        colaPedidos.setEncolar("c03", "Gorra", 25000);
        JOptionPane.showMessageDialog(this, "Gorra agregada");
    }//GEN-LAST:event_btnagActionPerformed

    private void btnacsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacsActionPerformed
        
        carrito.add("Camisa");
        historialPila.setPush("c06", "Camisa", 55000);
        colaPedidos.setEncolar("c06", "Camisa", 55000);
        JOptionPane.showMessageDialog(this, "Camisa agregada");
    }//GEN-LAST:event_btnacsActionPerformed

    private void btnajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajActionPerformed
        
        carrito.add("Jeans");
        historialPila.setPush("c02", "Jeans", 80000);
        colaPedidos.setEncolar("c02", "Jeans", 80000);
        JOptionPane.showMessageDialog(this,"Jeans agregado");
    }//GEN-LAST:event_btnajActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if (carrito.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El carrito ya está vacío");
        } else {
        carrito.clear();
        historialPila.tope = null; 
        colaPedidos.inicio = null;
        JOptionPane.showMessageDialog(this, "Carrito vaciado correctamente");
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btngcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngcActionPerformed
        
        if(carrito.isEmpty()){
            JOptionPane.showMessageDialog(this, "No hay productos para guardar");
            return;
        }
        
        try{
    
            FileWriter archivo = new FileWriter("carrito.txt");
    
            for(String p : carrito){
                archivo.write(p + "\n");
            }
    
            archivo.close();
    
            JOptionPane.showMessageDialog(this, "Carrito guardado correctamente");
            
        }catch(IOException e){
    
            JOptionPane.showMessageDialog(this, "Error al guardar archivo");
        }
    }//GEN-LAST:event_btngcActionPerformed

    private void btnepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnepActionPerformed
        
        if(carrito.isEmpty()){
            JOptionPane.showMessageDialog(this,"El carrito está vacío");
            
        }else{
            carrito.remove(carrito.size() - 1);
            
            JOptionPane.showMessageDialog(this, "Último producto eliminado");
        }
    }//GEN-LAST:event_btnepActionPerformed

    private void btnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhActionPerformed
        
        JOptionPane.showMessageDialog(this, historialPila.getHistorial());
    }//GEN-LAST:event_btnhActionPerformed

    private void btndhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndhActionPerformed
        
        Nodo extraido = historialPila.getPop();
        
        if (extraido != null) {
        
            
            if (!carrito.isEmpty()) {
            carrito.remove(carrito.size() - 1);
        }
        colaPedidos.setDesencolar();
        JOptionPane.showMessageDialog(this, "Se deshizo el último elemento agregado: " + extraido.nomP);
    }

    }//GEN-LAST:event_btndhActionPerformed

    private void btngpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngpActionPerformed
        
        colaPedidos.setGuardarPedidos();
    }//GEN-LAST:event_btngpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogo_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogo_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogo_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogo_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogo_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnac;
    private javax.swing.JButton btnacs;
    private javax.swing.JButton btnag;
    private javax.swing.JButton btnaj;
    private javax.swing.JButton btnam;
    private javax.swing.JButton btnap;
    private javax.swing.JButton btnaz;
    private javax.swing.JButton btndh;
    private javax.swing.JButton btnep;
    private javax.swing.JButton btngc;
    private javax.swing.JButton btngp;
    private javax.swing.JButton btnh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
